home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

materials/urls.py
from django.urls import path
from . import views


app_name = 'materials'
urlpatterns = [
    path('', views.index, name='index'),
    path('deleted/', views.deleted, name='deleted'),
    path('edit/<int:material_id>/', views.edit, name='edit'),
    path('save/', views.save, name='save'),
    path('delete/', views.delete, name='delete'),
]

pfsmanager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('materials/', include('materials.urls')),
    path('products/', include('products.urls')),
    path('shop/', include('shop.urls')),
    path('logs/', include('logs.urls')),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'
urlpatterns = [
    path('', views.list, name='index'),
    path('json/', views.json, name='json'),
    path('list/', views.list, name='list'),
    path('list/<str:category>/', views.list, name='list'),
    path('edit/<str:category>/<int:object_id>/', views.edit, name='edit'),
    path('save/<str:category>/', views.save, name='save'),
    path('delete/<str:category>/', views.delete, name='delete'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.quotes, name='index'),
    path('quotes/', views.quotes, name='quotes'),
    path('quote_edit/<int:quote_id>/', views.quote_edit, name='quote_edit'),
    path('quote_save', views.quote_save, name='quote_save'),
    path('quote_delete', views.quote_delete, name='quote_delete'),
]

home/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    return render(request, 'home/index.html')

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}PFS Manager{% endblock %}</title>

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-98498716-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'UA-98498716-1');
        </script>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'plugins/bootstrap/4/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'plugins/fontawesome/5/css/all.min.css' %}">

        <style media="screen">
            .table-col-no
            {
                width: 2rem;
            }
            .table-col-code
            {
                width: 5rem;
            }
            .table-col-remove
            {
                width: 5rem;
            }
            .table-col-quantity
            {
                width: 5rem;
            }
            .table-col-price
            {
                width: 8rem;
            }
            .table-col-date
            {
                width: 10rem;
            }
            .table-col-action
            {
                width: 12rem;
            }
        </style>
        {% block styles %}{% endblock %}
    </head>
    <body>

        {% block navbar %}{% endblock %}

        {% load tz %}

        <div class="container my-3">
            {% block content %}{% endblock %}
        </div>

        {% block modals %}{% endblock %}

        <script src="{% static 'plugins/jquery/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'plugins/bootstrap/4/js/bootstrap.bundle.min.js' %}"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>

home/templates/home/index.html
{% extends "home/base.html" %}

{% block title %}PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='' %}
{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="display-1">
        Home
    </div>
</div>
{% endblock %}

home/templates/home/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:index' %}">PFS Manager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-content">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link {% if navbar_tab == 'shop' %}active{% endif %}" href="{% url 'shop:index' %}">Shop</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if navbar_tab == 'products' %}active{% endif %}" href="{% url 'products:index' %}">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if navbar_tab == 'materials' %}active{% endif %}" href="{% url 'materials:index' %}">Raw Materials</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" data-toggle="dropdown">
                        Account
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'admin:logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>