home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

materials/urls.py
from django.urls import path
from . import views


app_name = 'materials'
urlpatterns = [
    path('', views.index, name='index'),
    path('deleted/', views.deleted, name='deleted'),
    path('edit/<int:material_id>/', views.edit, name='edit'),
    path('save/', views.save, name='save'),
    path('delete/', views.delete, name='delete'),
]

pfsmanager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('materials/', include('materials.urls')),
    path('products/', include('products.urls')),
    path('shop/', include('shop.urls')),
    path('logs/', include('logs.urls')),
]

materials/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import Truncator


class Material(models.Model):
    name = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=True)
    quantity = models.IntegerField(default=0)
    date_purchased = models.DateField(default=timezone.localdate)
    deleted = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(default=timezone.now)
    datetime_updated = models.DateTimeField(null=True, blank=True)
    datetime_deleted = models.DateTimeField(null=True, blank=True)

    def form(self, form):
        self.name = form.get('name', '')
        self.description = form.get('description', '')
        self.quantity = form.get('quantity', 0)
        self.date_purchased = form.get('date_purchased', timezone.localdate)

    def is_valid(self):
        if not self.name:
            return False
        return True

    def short_description(self, word_count=15):
        return Truncator(self.description).words(word_count)

materials/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from .models import Material
from logs.models import Log


@login_required
def index(request):
    materials = Material.objects.filter(deleted=False).order_by('-id')[:30]
    data = { 'materials': materials }
    return render(request, 'materials/latest.html', data)


@login_required
def deleted(request):
    materials = Material.objects.filter(deleted=True).order_by('-id')[:30]
    data = { 'materials': materials }
    return render(request, 'materials/deleted.html', data)


@login_required
def edit(request, material_id=0):
    material = None
    try:
        material = Material.objects.get(id=material_id)
    except ObjectDoesNotExist:
        material = Material()
        material.id = 0
    data = { 'material': material }
    return render(request, 'materials/edit.html', data)


@login_required
def save(request):
    material_id = request.POST.get('material_id', 0)
    next = request.POST.get('next', 'list')
    action = 'create'
    if request.method == 'POST':
        material = Material()
        if int(material_id) > 0:
            material.id = material_id
            action = 'update'
            material.datetime_updated = timezone.now()
        material.form(request.POST)
        material.user = request.user
        if material.is_valid():
            material.save()
            Log.objects.create(
                object = 'Material',
                object_id = material.id,
                action = action,
                user = request.user
            )
            if next == 'add':
                return redirect('materials:edit', 0)
            return redirect('materials:index')
    return redirect('materials:edit', material_id)


@login_required
def delete(request):
    material_id = request.POST.get('material_id', 0)
    if request.method == 'POST':
        try:
            material = Material.objects.get(id=material_id)
            material.deleted = True
            material.datetime_deleted = timezone.now()
            material.save()
            Log.objects.create(
                object = 'Material',
                object_id = material.id,
                action = 'delete',
                user = request.user
            )
        except ObjectDoesNotExist:
            material = None
    return redirect('materials:index')

materials/templates/materials/deleted.html
{% extends "home/base.html" %}

{% block title %}Deleted Raw Materials - PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='materials' %}
{% endblock %}

{% block content %}
{% include 'materials/menu.html' with menu_tab='deleted' %}

<div class="card mb-4">
    <div class="card-header">
        Deleted Raw materials
    </div>
    <table id="table-accordion" class="table table-hover table-bordered accordion mb-0">
        <thead>
            <tr>
                <th class="table-col-no">#</th>
                <th>Name</th>
                <th class="table-col-quantity d-none d-md-table-cell">Quantity</th>
                <th class="table-col-date d-none d-md-table-cell">Date Purchased</th>
            </tr>
        </thead>
        <tbody>
{% for material in materials %}
            <tr data-toggle="collapse" data-target="#material-{{material.id}}">
                <td>{{forloop.counter}}</td>
                <td>
                    {{material.name}}
                    <div id="material-{{material.id}}" class="collapse small" data-parent="#table-accordion">
                        <hr>
                        <p class="mb-0">Description: {{ material.description }}</p>
                        <p class="d-md-none mb-0">Quantity: {{ material.quantity }}</p>
                        <p class="d-md-none mb-0">Date Purchased: {{ material.date_purchased }}</p>
                        <p class="mb-0">Added by {{ material.user }}</p>
                    </div>
                </td>
                <td class="d-none d-md-table-cell">{{ material.quantity }}</td>
                <td class="d-none d-md-table-cell">{{ material.date_purchased }}</td>
            </tr>
{% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

materials/templates/materials/edit.html
{% extends "home/base.html" %}

{% block title %}Edit Raw Material info - PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='materials' %}
{% endblock %}

{% block content %}
<a href="{% url 'materials:index' %}" class="btn btn-link mb-4">Back to Raw Materials list</a>
<div class="card mb-4">
    <div class="card-header">
        Raw Material Info
    </div>
    <div class="card-body">
        <form class="" action="{% url 'materials:save' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="material_id" value="{{ material.id }}">
            <fieldset class="mb-4">
                <div class="form-group row">
                    <label for="form-material-name" class="col-md-2 col-form-label">Name</label>
                    <div class="col-md-10">
                        <input type="text" class="form-control" id="form-material-name" name="name"
                            placeholder="Enter name" maxlength="255" value="{{ material.name }}" required>
                        <small id="form-material-name-help" class="form-text text-muted">Name for a common call of the item</small>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-material-description" class="col-md-2 col-form-label">Description (optional)</label>
                    <div class="col-md-10">
                        <textarea class="form-control" rows="5" name="description"
                            placeholder="Enter description">{{ material.description }}</textarea>
                        <small id="form-material-description-help" class="form-text text-muted">Long description for more information</small>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-material-quantity" class="col-md-2 col-form-label">Quantity</label>
                    <div class="col-md-3">
                        <input type="number" class="form-control" id="form-material-quantity" name="quantity"
                            placeholder="Enter quantity" min="0" value="{{ material.quantity }}" required>
                        <small id="form-material-quantity-help" class="form-text text-muted">Count of the item</small>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-material-date_purchased" class="col-md-2 col-form-label">Date purchased</label>
                    <div class="col-md-3">
                        <input type="date" class="form-control" id="form-material-date_purchased" name="date_purchased"
                            placeholder="Enter date purchased" min="0" value="{{ material.date_purchased|date:"Y-m-d" }}" required>
                        <small id="form-material-date_purchased-help" class="form-text text-muted">Date the item was purchased</small>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <div class="form-group mb-0 row">
                    <div class="offset-md-2 col-md-3">
                        <button type="submit" class="btn btn-success"
                            name="next" value="list">Save</button>
                        <button type="submit" class="btn btn-success"
                            name="next" value="add">Save &amp; add another</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

materials/templates/materials/index.html
{% extends "home/base.html" %}

{% block title %}Raw Materials - PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='materials' %}
{% endblock %}

{% block content %}
{% include 'materials/menu.html' with menu_tab='latest' %}

<div class="card mb-4">
    <div class="card-header">
        Latest Raw materials
    </div>
    <table id="table-accordion" class="table table-hover table-bordered accordion mb-0">
        <thead>
            <tr>
                <th class="table-col-no">#</th>
                <th class="table-col-code d-none d-md-table-cell">Code</th>
                <th>Name</th>
                <th class="table-col-quantity d-none d-md-table-cell">Quantity</th>
                <th class="table-col-date d-none d-md-table-cell">Date Purchased</th>
                <th class="table-col-action">Action</th>
            </tr>
        </thead>
        <tbody>
{% for material in materials %}
            <tr data-toggle="collapse" data-target="#material-{{material.id}}">
                <td>{{forloop.counter}}</td>
                <td class="d-none d-md-table-cell">{{ material.code }}</td>
                <td>
                    <div class="d-md-none small">
                        [{{ material.code }}]
                    </div>
                    <p>{{ material.name }}</p>
                    <div id="material-{{material.id}}" class="collapse  small" data-parent="#table-accordion">
                        <dl class="row mb-0">
                            <dt class="col-sm-3">Description</dt>
                            <dd class="col-sm-9">{{ material.description }}</dd>
                        </dl>
                        <dl class="d-md-none row mb-0">
                            <dt class="col-sm-3">Quantity</dt>
                            <dd class="col-sm-9">{{ material.quantity }}</dd>
                        </dl>
                        <dl class="d-md-none row mb-0">
                            <dt class="col-sm-3">Date Purchased</dt>
                            <dd class="col-sm-9">{{ material.date_purchased }}</dd>
                        </dl>
                        <dl class="row mb-0">
                            <dt class="col-sm-3">Added by</dt>
                            <dd class="col-sm-9">{{ material.user }}</dd>
                        </dl>
                    </div>
                </td>
                <td class="d-none d-md-table-cell">{{ material.quantity }}</td>
                <td class="d-none d-md-table-cell">{{ material.date_purchased }}</td>
                <td>
                    <a class="text-info" href="{% url 'materials:edit' material.id %}">Edit</a>
                    &nbsp;
                    <a class="text-danger" href="javascript:prompt_delete({{material.id}})">Delete</a>
                </td>
            </tr>
{% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block modals %}
    <div id="modal-material-delete" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="{% url 'materials:delete' %}" method="post">
                    {% csrf_token %}
                    <input id="modal-material-delete-id" type="hidden" name="material_id" value="0">
                    <div class="modal-body">
                        Are you sure you want to delete this record?
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-sm btn-success" name="delete" value="1">Yes</button>
                        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">No</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    function prompt_delete(id)
    {
        $('#modal-material-delete-id').val(id);
        $('#modal-material-delete').modal('show');
    }
{% endblock %}

materials/templates/materials/latest.html
{% extends "home/base.html" %}

{% block title %}Raw Materials - PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='materials' %}
{% endblock %}

{% block content %}
{% include 'materials/menu.html' with menu_tab='latest' %}

<div class="card mb-4">
    <div class="card-header">
        Latest Raw materials
    </div>
    <table id="table-accordion" class="table table-hover table-bordered accordion mb-0">
        <thead>
            <tr>
                <th class="table-col-no">#</th>
                <th>Name</th>
                <th class="table-col-quantity d-none d-lg-table-cell">Quantity</th>
                <th class="table-col-date d-none d-md-table-cell">Date Purchased</th>
                <th class="table-col-action d-none d-md-table-cell">Action</th>
            </tr>
        </thead>
        <tbody>
{% for material in materials %}
            <tr data-toggle="collapse" data-target="#material-{{material.id}}">
                <td>{{forloop.counter}}</td>
                <td>
                    <p>{{ material.name }}</p>
                    <div id="material-{{material.id}}" class="collapse  small" data-parent="#table-accordion">
                        <dl class="row mb-0">
                            <dt class="col-md-4 col-xl-2">Description</dt>
                            <dd class="col-md-8">{{ material.short_description }}</dd>
                        </dl>
                        <dl class="d-lg-none row mb-0">
                            <dt class="col-md-4 col-xl-2">Quantity</dt>
                            <dd class="col-md-8">{{ material.quantity }}</dd>
                        </dl>
                        <dl class="d-md-none row mb-0">
                            <dt class="col-md-4 col-xl-2">Date Purchased</dt>
                            <dd class="col-md-8">{{ material.date_purchased }}</dd>
                        </dl>
                        <dl class="row mb-0">
                            <dt class="col-md-4 col-xl-2">Added by</dt>
                            <dd class="col-md-8">{{ material.user }}</dd>
                        </dl>
                    </div>
                    <div class="d-md-none">
                        <a class="btn btn-sm btn-info" href="{% url 'materials:edit' material.id %}">Edit</a>
                        <a class="btn btn-sm btn-danger" href="javascript:prompt_delete({{material.id}})">Delete</a>
                    </div>
                </td>
                <td class="d-none d-lg-table-cell">{{ material.quantity }}</td>
                <td class="d-none d-md-table-cell">{{ material.date_purchased }}</td>
                <td class="d-none d-md-table-cell">
                    <a class="btn btn-sm btn-info" href="{% url 'materials:edit' material.id %}">Edit</a>
                    <a class="btn btn-sm btn-danger" href="javascript:prompt_delete({{material.id}})">Delete</a>
                </td>
            </tr>
{% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block modals %}
    <div id="modal-material-delete" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="{% url 'materials:delete' %}" method="post">
                    {% csrf_token %}
                    <input id="modal-material-delete-id" type="hidden" name="material_id" value="0">
                    <div class="modal-body">
                        Are you sure you want to delete this record?
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-sm btn-success" name="delete" value="1">Yes</button>
                        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">No</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    function prompt_delete(id)
    {
        $('#modal-material-delete-id').val(id);
        $('#modal-material-delete').modal('show');
    }
</script>
{% endblock %}

materials/templates/materials/menu.html
<ul class="nav nav-tabs mb-4">
    <li class="nav-item">
        <a class="nav-link {% if menu_tab == 'latest' %}active{% endif %}"
            href="{% url 'materials:index' %}">Latest</a>
    </li>
    <li class="ml-auto nav-item">
        <a class="nav-link" href="{% url 'materials:edit' 0 %}">Add new raw material</a>
    </li>
</ul>