home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

pfsmanager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('materials/', include('materials.urls')),
    path('products/', include('products.urls')),
    path('shop/', include('shop.urls')),
    path('logs/', include('logs.urls')),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'
urlpatterns = [
    path('', views.list, name='index'),
    path('json/', views.json, name='json'),
    path('list/', views.list, name='list'),
    path('list/<str:category>/', views.list, name='list'),
    path('edit/<str:category>/<int:object_id>/', views.edit, name='edit'),
    path('save/<str:category>/', views.save, name='save'),
    path('delete/<str:category>/', views.delete, name='delete'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.quotes, name='index'),
    path('quotes/', views.quotes, name='quotes'),
    path('quote_edit/<int:quote_id>/', views.quote_edit, name='quote_edit'),
    path('quote_save', views.quote_save, name='quote_save'),
    path('quote_delete', views.quote_delete, name='quote_delete'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import Truncator
from products.models import Product


class Quote(models.Model):
    number = models.CharField(max_length=15, blank=False, unique=True)
    date = models.DateField(default=timezone.localdate)
    payment_mode = models.CharField(max_length=30, default='')
    payment_terms = models.CharField(max_length=30, default='')
    discount = models.DecimalField(max_digits=8, decimal_places=2)
    gst = models.IntegerField(default=0)
    deleted = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(default=timezone.now)
    datetime_updated = models.DateTimeField(null=True, blank=True)
    datetime_deleted = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return 'Quote # %s' % self.number

    def form(self, form):
        self.number = form.get('number', '')
        self.date = form.get('date', timezone.localdate())
        self.payment_mode = form.get('payment_mode', '')
        self.payment_terms = form.get('payment_terms', '')
        self.discount = form.get('discount', 0)
        self.gst = form.get('gst', 0)

    def is_valid(self):
        if not self.number:
            return False
        if not self.date:
            return False
        return True


class QuoteProducts(models.Model):
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)


class Client(models.Model):
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE)
    person_name = models.CharField(max_length=128, blank=False)
    person_phone = models.CharField(max_length=30, blank=False)
    person_address = models.TextField(blank=True)
    person_deceased_relationship = models.CharField(max_length=30, blank=False)
    contact_name = models.CharField(max_length=128, blank=False)
    contact_phone = models.CharField(max_length=30, blank=False)
    deceased_name = models.CharField(max_length=128, blank=False)
    deceased_date_birth = models.DateField(default=timezone.localdate)
    deceased_date_death = models.DateField(default=timezone.localdate)
    delivery_datetime = models.DateTimeField(default=timezone.now)
    delivery_notes = models.TextField(blank=True)
    pickup_datetime = models.DateTimeField(default=timezone.now)
    pickup_notes = models.TextField(blank=True)
    deleted = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(default=timezone.now)
    datetime_updated = models.DateTimeField(null=True, blank=True)
    datetime_deleted = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return '%s: %s' % (self.quote, self.person_name)

    def form(self, form):
        self.person_name = form.get('person_name', '')
        self.person_phone = form.get('person_phone', '')
        self.person_address = form.get('person_address', '')
        self.person_deceased_relationship = form.get('person_deceased_relationship', '')
        self.contact_name = form.get('contact_name', '')
        self.contact_phone = form.get('contact_phone', '')
        self.deceased_name = form.get('deceased_name', '')
        self.deceased_date_birth = form.get('deceased_date_birth', timezone.localdate)
        self.deceased_date_death = form.get('deceased_date_death', timezone.localdate)
        self.delivery_datetime = form.get('delivery_datetime', timezone.now)
        self.delivery_notes = form.get('delivery_notes', '')
        self.pickup_datetime = form.get('pickup_datetime', timezone.now)
        self.pickup_notes = form.get('pickup_notes', '')

    def is_valid(self):
        if not self.person_name:
            return False
        if not self.contact_name:
            return False
        if not self.deceased_name:
            return False
        return True


class ClientFile(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    type = models.CharField(max_length=15, blank=False)
    file = models.FileField(upload_to='documents', default='', blank=True)

shop/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from .models import Quote, Client
from logs.models import Log


@login_required
def quotes(request):
    quotes = Quote.objects.filter(deleted=False).order_by('-id')[:30]
    data = { 'quotes': quotes }
    return render(request, 'shop/quotes.html', data)


@login_required
def quote_edit(request, quote_id=0):
    quote = None
    try:
        quote = Quote.objects.get(id=quote_id)
    except ObjectDoesNotExist:
        quote = Quote()
        quote.id = 0
    data = { 'quote': quote }
    return render(request, 'shop/quote_edit.html', data)


@login_required
def quote_save(request):
    quote_id = request.POST.get('quote_id', 0)
    action = 'create'
    if request.method == 'POST':
        quote = Quote()
        try:
            if int(quote_id) > 0:
                quote.id = quote_id
                action = 'update'
                quote.datetime_updated = timezone.now()
        except ValueError as e:
            quote.id = 0
        quote.form(request.POST)
        quote.user = request.user
        # if quote.is_valid():
        #     try:
        #         quote.save()
        #         Log.objects.create(
        #             object = 'Quote:',
        #             object_id = quote.id,
        #             action = action,
        #             user = request.user
        #         )
        #     except IntegrityError as e:
        #         quote = None
    return JsonResponse({
        'quote': {
            'id': quote_id,
            'number': quote.number,
            'date': quote.date,
            'payment_mode': quote.payment_mode,
            'payment_terms': quote.payment_terms,
            'discount': quote.discount,
            'gst': quote.gst,
            'products': request.POST.get('products', '')

        }
    })


@login_required
def quote_delete(request):
    quote_id = request.POST.get('quote_id', 0)
    if request.method == 'POST':
        try:
            quote = Quote.objects.get(id=quote_id)
            quote.deleted = True
            quote.datetime_deleted = timezone.now()
            quote.save()
            Log.objects.create(
                object = 'Quote',
                object_id = quote.id,
                action = 'delete',
                user = request.user
            )
        except ObjectDoesNotExist:
            quote = None
    return redirect('shop:quotes')

shop/templates/shop/menu.html
<ul class="nav nav-tabs mb-4">
    <li class="nav-item">
        <a class="nav-link {% if menu_tab == 'quotes' %}active{% endif %}" href="{% url 'shop:quotes' %}">Quotations</a>
    </li>
    <li class="ml-auto nav-item">
{% if menu_tab == 'quotes' %}
        <a class="nav-link" href="{% url 'shop:quote_edit' 0 %}">Add new quotation</a>
{% endif %}
    </li>
</ul>

shop/templates/shop/quote_edit.html
{% extends "home/base.html" %}

{% block title %}Edit Quotation - PFS Manager{% endblock %}

{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}" />
<style media="screen">
    #cart-row td *
    {
        visibility: hidden;
    }
</style>
{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='shop' %}
{% endblock %}

{% block content %}
<a href="{% url 'shop:quotes' %}" class="btn btn-link mb-4">Back to Quotations list</a>
<div class="row">
    <div class="col-md-4 col-lg-3">
        <div class="input-group input-group-lg">
            <div class="input-group-prepend">
                <span class="input-group-text">Quote #</span>
            </div>
            <input id="form-quote-number" type="number" class="form-control" value="0" min="0" max="100000">
        </div>
    </div>
    <div class="col-md-4 offset-md-4 offset-lg-5">
        <div class="input-group input-group-lg mb-4">
            <div class="input-group-prepend">
                <span class="input-group-text">Date</span>
            </div>
            <input id="form-quote-date" type="date" class="form-control">
        </div>
    </div>
</div>
<div class="card mb-4">
    <div class="card-header">
        <div class="row align-items-center">
            <div class="col-md-6 col-lg-8">
                <h4 class="mb-0">Cart</h4>
            </div>
            <div class="col-md-6 col-lg-4">
                <select id="form-product-search" class="custom-select"></select>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table id="cart-table" class="table table-bordered table-hover mb-0">
            <thead>
                <th class="table-col-no text-center">#</th>
                <th class="text-center">Product</th>
                <td class="table-col-remove text-center">Remove</td>
                <th class="table-col-price text-center">Unit Price</th>
                <th class="table-col-quantity text-center">Quantity</th>
                <th class="table-col-price text-center">Price</th>
            </thead>
            <tbody>
                <tr id="cart-row" data-product_id="0">
                    <td class="cart-row-no">
                        <span>0</span>
                    </td>
                    <td class="cart-row-name">
                        <span></span>
                    </td>
                    <td class="cart-row-remove text-center">
                        <a class="text-danger" href="#">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                    <td class="cart-row-unit_price text-right">
                        <span>0.00</span>
                    </td>
                    <td class="cart-row-quantity">
                        <input class="form-control form-control-sm" type="number" value="1" min="1">
                    </td>
                    <td class="cart-row-price text-right">
                        <span>0.00</span>
                    </td>
                </tr>
                <tr id="cart-row-sub_total" class="table-warning">
                    <td colspan="3"></td>
                    <th class="cart-row-name text-right" colspan="2">Sub Total</th>
                    <th class="cart-row-price text-right">0.00</th>
                </tr>
                <tr id="cart-row-gst">
                    <td colspan="3"></td>
                    <th class="cart-row-name text-right" colspan="2">
                        <div class="input-group input-group-sm">
                            <input id="form-quote-gst" type="number" class="form-control form-control-sm text-right"
                                placeholder="GST" value="10" min="0" max="100">
                            <div class="input-group-append">
                                <span class="input-group-text">% GST</span>
                            </div>
                        </div>
                    </th>
                    <td class="cart-row-price text-right">0.00</td>
                </tr>
                <tr id="cart-row-total">
                    <td colspan="3"></td>
                    <th class="cart-row-name text-right" colspan="2">Total</th>
                    <td class="cart-row-price text-right">0.00</td>
                </tr>
                <tr id="cart-row-discount">
                    <td colspan="3"></td>
                    <th class="cart-row-name text-right" colspan="2">Discount</th>
                    <td class="cart-row-price">
                        <input id="form-quote-discount" class="form-control form-control-sm text-right" type="number" value="0.00" min="0">
                    </td>
                </tr>
                <tr id="cart-row-net_total" class="table-success">
                    <td colspan="3"></td>
                    <th class="cart-row-name text-right" colspan="2">Net Total</th>
                    <th class="cart-row-price text-right">0.00</th>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-4 col-lg-3">
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Payment mode</span>
            </div>
            <input id="form-quote-payment_mode" type="text" class="form-control" value="">
        </div>
    </div>
    <div class="col-md-4 offset-md-4 offset-lg-5">
        <div class="input-group mb-4">
            <div class="input-group-prepend">
                <span class="input-group-text">Payment terms</span>
            </div>
            <input id="form-quote-payment_terms" type="text" class="form-control" value="">
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <button id="form-btn-save" class="btn btn-success btn-lg" type="button">Save</button>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% csrf_token %}
<script src="{% static 'plugins/select2/js/select2.min.js' %}"></script>
<script type="text/javascript">
    var products = {};
    var cart = {};

    var quote = {
            id: 0,
            number: '',
            date: '',
            payment_mode: '',
            payment_terms: '',
            discount: 0,
            gst: 0
    };

    $(function() {

        $('#form-product-search').select2({
            ajax: {
                url: '{% url 'products:json' %}',
                delay: 500,
                dataType: 'json',
                type: 'get',
                data: function (params) {
                    return {
                        category: $('#form-product-search-category').val(),
                        name: params.term,
                        limit: 10,
                        page: params.page || 1
                    };
                },
                processResults: function (data, params) {
                    params.page = params.page || 1;
                    return {
                        results: $.map(data.products, function (product) {
                            products[product.id] = product;
                            return {
                                id: product.id,
                                text: '[' + product.code + '] ' + product.name
                            };
                        }),
                        pagination: {
                            more: (params.page * 10) < data.products.length
                        }
                    };
                }
            },
            minimumInputLength: 1,
            placeholder: 'Search products'
        });

        $('#form-product-search').on('change', function() {
            id = $(this).val();
            if (id > 0) addToCart(id);
            else return;
            $('#form-product-search').val(null).trigger('change');
        });

        $('.cart-row-quantity input').on('change', function() {
            parent_row = $(this).parents('tr');
            product_id = parent_row.data('product_id');
            cart[product_id].quantity = $(this).val();
            row_price = products[product_id].price * cart[product_id].quantity;
            parent_row.find('.cart-row-price').html(printMoney(row_price));

            calculate();
        });

        $('.cart-row-remove a').on('click', function() {
            parent_row = $(this).parents('tr');
            product_id = parent_row.data('product_id');
            removeFromCart(product_id);
            parent_row.remove();
        });

        $('#cart-row-gst input').on('change', function() {
            calculate();
        });

        $('#cart-row-discount input').on('change', function() {
            calculate();
        });

        $('#form-quote-number').on('change', function() {
            quote.number = $(this).val();
        });

        $('#form-btn-save').on('click', save);

    });

    function addToCart(product_id)
    {
        if (cart[product_id]) return;
        cart[product_id] = { 'id': product_id, 'quantity': 1 };

        row_no = Object.keys(cart).length
        row_name = '[' + products[product_id].code + '] ' + products[product_id].name;
        row_price = products[product_id].price;
        row_quantity = 1;

        table_row = $('#cart-row').clone(true);
        table_row.removeAttr('id');
        table_row.data('product_id', product_id);
        table_row.find('.cart-row-no').html(row_no);
        table_row.find('.cart-row-name').html(row_name);
        table_row.find('.cart-row-unit_price').html(printMoney(row_price));
        table_row.find('.cart-row-quantity input').val(row_quantity);
        table_row.find('.cart-row-price').html(printMoney(row_price));

        table_row.insertBefore('#cart-row');

        calculate();
    }

    function removeFromCart(product_id)
    {
        if (!cart[product_id]) return;

        delete cart[product_id];
        calculate();
    }

    function calculate()
    {
        sub_total = 0.00;
        $.each(cart, function(key, value) {
            sub_total += products[value.id].price * value.quantity;
        });
        $('#cart-row-sub_total .cart-row-price').html(printMoney(sub_total));

        gst = $('#cart-row-gst input').val();
        gst_price = gst/100 * sub_total;
        $('#cart-row-gst .cart-row-price').html(printMoney(gst_price));

        total = sub_total + gst_price;
        $('#cart-row-total .cart-row-price').html(printMoney(total));

        discount = $('#cart-row-discount input').val();
        net_total = Math.max(0, total - discount);
        $('#cart-row-net_total .cart-row-price').html(printMoney(net_total));
    }

    function printMoney(money)
    {
        money = money * 1;
        return money.toLocaleString(undefined, {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2
        });
    }

    function save()
    {
        if (quote.number) {
            quote.number = $('#form-quote-number').val();
            quote.date = $('#form-quote-date').val();
            quote.payment_mode = $('#form-quote-payment_mode').val();
            quote.payment_terms = $('#form-quote-payment_terms').val();
            quote.discount = $('#form-quote-discount').val();
            quote.gst = $('#form-quote-gst').val();
            quote.products = [];

            $.each(cart, function(key, value) {
                quote.products.push(value);
            });

            console.log(quote.products);

            $.ajax({
                url: '{% url 'shop:quote_save' %}',
                dataType: 'json',
                type: 'post',
                data: $.param({
                    'quote_id': quote.id,
                    'number': quote.number,
                    'date': quote.date,
                    'payment_mode': quote.payment_mode,
                    'payment_terms': quote.payment_terms,
                    'discount': quote.discount,
                    'gst': quote.gst,
                    'products': $.param(cart),
                    'csrfmiddlewaretoken': $('[name=csrfmiddlewaretoken]').val()
                }),
                success: function(data) {
                    console.log(data);
                }
            });
        }
        return false;
    }

</script>
{% endblock %}

shop/templates/shop/quotes.html
{% extends "home/base.html" %}

{% block title %}Quotations - PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='shop' %}
{% endblock %}

{% block content %}
{% include 'shop/menu.html' with menu_tab='quotes' %}

<div class="card mb-4">
    <div class="card-header">
        Quotations
    </div>
    <table id="table-accordion" class="table table-hover table-bordered accordion mb-0">
        <thead>
            <tr>
                <th class="table-col-no">#</th>
                <th class="table-col-code d-none d-md-table-cell">Quote #</th>
                <th class="table-col-date d-none d-md-table-cell">Date</th>
                <th class="table-col-action">Action</th>
            </tr>
        </thead>
        <tbody>
{% for quote in quotes %}
            <tr data-toggle="collapse" data-target="#quote-{{quote.id}}">
                <td>{{ forloop.counter }}</td>
                <td class="d-none d-md-table-cell">{{ quote.number }}</td>
                <td>
                    <p>{{ quote.number }}</p>
                    <div id="quote-{{quote.id}}" class="collapse small" data-parent="#table-accordion">
                        <dl class="d-md-none row mb-0">
                            <dt class="col-sm-3 col-lg-2">Date</dt>
                            <dd class="col-sm-9">{{ quote.date }}</dd>
                        </dl>
                        <dl class="row mb-0">
                            <dt class="col-sm-3 col-lg-2">Added by</dt>
                            <dd class="col-sm-9">{{ quote.user }}</dd>
                        </dl>
                    </div>
                </td>
                <td class="d-none d-md-table-cell">{{ quote.date }}</td>
                <td>
                    <a class="text-info" href="{% url 'shop:quote_edit' quote.id %}">Edit</a>
                    &nbsp;
                    <a class="text-danger" href="javascript:prompt_delete({{ quote.id }})">Delete</a>
                </td>
            </tr>
{% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block modals %}
    <div id="modal-quote-delete" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="{% url 'shop:quote_delete' %}" method="post">
                    {% csrf_token %}
                    <input id="modal-quote-delete-id" type="hidden" name="quote_id" value="0">
                    <div class="modal-body">
                        Are you sure you want to delete this record?
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-sm btn-success">Yes</button>
                        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">No</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    function prompt_delete(id)
    {
        $('#modal-quote-delete-id').val(id);
        $('#modal-quote-delete').modal('show');
    }
</script>
{% endblock %}