home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

pfsmanager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('materials/', include('materials.urls')),
    path('products/', include('products.urls')),
    path('shop/', include('shop.urls')),
    path('logs/', include('logs.urls')),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'
urlpatterns = [
    path('', views.list, name='index'),
    path('json/', views.json, name='json'),
    path('list/', views.list, name='list'),
    path('list/<str:category>/', views.list, name='list'),
    path('edit/<str:category>/<int:object_id>/', views.edit, name='edit'),
    path('save/<str:category>/', views.save, name='save'),
    path('delete/<str:category>/', views.delete, name='delete'),
]

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import Truncator


class Product(models.Model):
    category = models.CharField(max_length=15, blank=False)
    code = models.CharField(max_length=15, blank=False, unique=True)
    name = models.CharField(max_length=50, blank=False)
    description = models.TextField(blank=True)
    design = models.CharField(max_length=255, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    deleted = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(default=timezone.now)
    datetime_updated = models.DateTimeField(null=True, blank=True)
    datetime_deleted = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return '[' + self.code + '] ' + self.name

    def form(self, form):
        self.code = form.get('code', '')
        self.name = form.get('name', '')
        self.description = form.get('description', '')
        self.design = form.get('design', '')
        self.price = form.get('price', 0.00)

    def is_valid(self):
        if not self.name:
            return False
        return True

    def short_description(self, word_count=15):
        return Truncator(self.description).words(word_count)

    def print_price(self):
        return "{0:,.2f}".format(self.price)

products/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError
from django.utils import timezone
from .models import Product
from logs.models import Log


@login_required
def json(request, category='coffin'):
    param_name = request.GET.get('name', '')
    param_category = request.GET.get('category', '')
    param_limit = int(request.GET.get('limit', 10))
    param_page = int(request.GET.get('page', 1))
    param_offset = param_limit * (param_page - 1)
    products = Product.objects.filter(deleted=False, name__icontains=param_name, category__contains=param_category).order_by('-id')[param_offset:param_limit]
    json_products = {}
    for product in products:
        json_products[product.id] = {
            'id': product.id,
            'category': product.category,
            'code': product.code,
            'name': product.name,
            'description': product.description,
            'design': product.design,
            'price': product.price
        }
    return JsonResponse({
        'products': json_products
    })


@login_required
def list(request, category='coffin'):
    products = Product.objects.filter(category=category, deleted=False).order_by('-id')[:30]
    if category == 'service':
        data = { 'services': products }
        template = 'products/services.html'
    else:
        data = { 'coffins': products }
        template = 'products/coffins.html'
    return render(request, template, data)


@login_required
def edit(request, category, object_id=0):
    product = None
    try:
        product = Product.objects.get(id=object_id)
    except ObjectDoesNotExist:
        product = Product()
        product.id = 0
        product.category = category
    if category == 'service':
        data = { 'service': product }
        template = 'products/service_edit.html'
    else:
        data = { 'coffin': product }
        template = 'products/coffin_edit.html'
    return render(request, template, data)


@login_required
def save(request, category):
    object_id = request.POST.get('object_id', 0)
    next = request.POST.get('next', 'list')
    action = 'create'
    if request.method == 'POST':
        product = Product()
        try:
            if int(object_id) > 0:
                product.id = object_id
                action = 'update'
                product.datetime_updated = timezone.now()
        except ValueError as e:
            product.id = 0
        product.category = category
        product.form(request.POST)
        product.user = request.user
        if product.is_valid():
            try:
                product.save()
                Log.objects.create(
                    object = 'Product:' + category,
                    object_id = product.id,
                    action = action,
                    user = request.user
                )
                if next == 'add':
                    return redirect('products:edit', category, 0)
                return redirect('products:list', category)
            except IntegrityError as e:
                product = None
    return redirect('products:edit', category, object_id)


@login_required
def delete(request, category):
    object_id = request.POST.get('object_id', 0)
    if request.method == 'POST':
        try:
            product = Product.objects.get(id=object_id)
            product.deleted = True
            product.datetime_deleted = timezone.now()
            product.save()
            Log.objects.create(
                object = 'Product:' + category,
                object_id = product.id,
                action = 'delete',
                user = request.user
            )
        except ObjectDoesNotExist:
            product = None
    return redirect('products:list', category)

products/templates/products/categories.html
{% extends "home/base.html" %}

{% block title %}Product Categories - PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='products' %}
{% endblock %}

{% block content %}
{% include 'products/menu.html' with menu_tab='categories' %}

<div class="card mb-4">
    <div class="card-header">
        Product Categories
    </div>
    <table id="table-accordion" class="table table-hover table-bordered accordion mb-0">
        <thead>
            <tr>
                <th class="table-col-no">#</th>
                <th>Name</th>
                <th class="table-col-action">Action</th>
            </tr>
        </thead>
        <tbody>
{% for category in categories %}
            <tr data-toggle="collapse" data-target="#category-{{category.id}}">
                <td>{{ forloop.counter }}</td>
                <td>
                    {{ category.name }}
                    <div id="category-{{category.id}}" class="collapse small" data-parent="#table-accordion">
                        <hr>
                        <p>Added by {{ category.user }}</p>
                    </div>
                </td>
                <td>
                    <a class="text-info" href="{% url 'products:category_edit' category.id %}">Edit</a>
                    &nbsp;
                    <a class="text-danger" href="javascript:prompt_delete({{category.id}})">Delete</a>
                </td>
            </tr>
{% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block modals %}
    <div id="modal-category-delete" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="{% url 'products:category_delete' %}" method="post">
                    {% csrf_token %}
                    <input id="modal-category-delete-id" type="hidden" name="category_id" value="0">
                    <div class="modal-body">
                        Are you sure you want to delete this record?
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-sm btn-success">Yes</button>
                        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">No</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    function prompt_delete(id)
    {
        $('#modal-category-delete-id').val(id);
        $('#modal-category-delete').modal('show');
    }
{% endblock %}

products/templates/products/coffin_edit.html
{% extends "home/base.html" %}

{% block title %}Edit Product - PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='products' %}
{% endblock %}

{% block content %}
<a href="{% url 'products:list' 'coffin' %}" class="btn btn-link mb-4">Back to Coffins list</a>
<div class="card mb-4">
    <div class="card-header">
        Coffin Info
    </div>
    <div class="card-body">
        <form class="" action="{% url 'products:save' 'coffin' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="object_id" value="{{ coffin.id }}">
            <fieldset class="mb-4">
                <div class="form-group row">
                    <label for="form-coffin-code" class="col-md-2 col-form-label">Code</label>
                    <div class="col-md-3">
                        <input type="text" class="form-control" id="form-coffin-code" name="code"
                            placeholder="Enter code" maxlength="15" value="{{ coffin.code }}" required>
                        <small id="form-coffin-code-help" class="form-text text-muted">Code of the coffin</small>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-coffin-name" class="col-md-2 col-form-label">Name</label>
                    <div class="col-md-10">
                        <input type="text" class="form-control" id="form-coffin-name" name="name"
                            placeholder="Enter name" maxlength="255" value="{{ coffin.name }}" required>
                        <small id="form-coffin-name-help" class="form-text text-muted">Name of the coffin</small>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-coffin-description" class="col-md-2 col-form-label">Description</label>
                    <div class="col-md-10">
                        <textarea class="form-control" id="form-coffin-description" name="description"
                            rows="3" placeholder="Enter description">{{ coffin.description }}</textarea>
                        <small id="form-coffin-description-help" class="form-text text-muted">Description of the coffin</small>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-coffin-design" class="col-md-2 col-form-label">Design</label>
                    <div class="col-md-10">
                        <input type="text" class="form-control" id="form-coffin-design" name="colors"
                            placeholder="Enter design" maxlength="255" value="{{ coffin.design }}" required>
                        <small id="form-coffin-design-help" class="form-text text-muted">Design of the coffin</small>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-coffin-price" class="col-md-2 col-form-label">Price</label>
                    <div class="col-md-3">
                        <input type="number" class="form-control" id="form-coffin-price" name="price"
                            placeholder="Enter price" min="0" value="{{ coffin.price }}" required>
                        <small id="form-coffin-price-help" class="form-text text-muted">Price of the coffin</small>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <div class="form-group mb-0 row">
                    <div class="offset-md-2 col-md-3">
                        <button type="submit" class="btn btn-success"
                            name="next" value="list">Save</button>
                        <button type="submit" class="btn btn-success"
                            name="next" value="add">Save &amp; add another</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

products/templates/products/coffins.html
{% extends "home/base.html" %}

{% block title %}Coffins - PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='products' %}
{% endblock %}

{% block content %}
{% include 'products/menu.html' with menu_tab='coffins' %}

<div class="card mb-4">
    <div class="card-header">
        Coffins
    </div>
    <table id="table-accordion" class="table table-hover table-bordered accordion mb-0">
        <thead>
            <tr>
                <th class="table-col-no">#</th>
                <th class="table-col-code d-none d-md-table-cell">Code</th>
                <th>Name</th>
                <th class="table-col-price d-none d-md-table-cell">Price</th>
                <th class="table-col-action">Action</th>
            </tr>
        </thead>
        <tbody>
{% for coffin in coffins %}
            <tr data-toggle="collapse" data-target="#coffin-{{coffin.id}}">
                <td>{{ forloop.counter }}</td>
                <td class="d-none d-md-table-cell">{{ coffin.code }}</td>
                <td>
                    <div class="d-md-none small">
                        [{{ coffin.code }}]
                    </div>
                    <p>{{ coffin.name }}</p>
                    <div id="coffin-{{coffin.id}}" class="collapse small" data-parent="#table-accordion">
                        <dl class="row mb-0">
                            <dt class="col-sm-3 col-lg-2">Description</dt>
                            <dd class="col-sm-9">{{ coffin.short_description }}</dd>
                        </dl>
                        <dl class="row mb-0">
                            <dt class="col-sm-3 col-lg-2">Design</dt>
                            <dd class="col-sm-9">{{ coffin.design }}</dd>
                        </dl>
                        <dl class="d-md-none row mb-0">
                            <dt class="col-sm-3 col-lg-2">Price</dt>
                            <dd class="col-sm-9">PGK {{ coffin.print_price }}</dd>
                        </dl>
                        <dl class="row mb-0">
                            <dt class="col-sm-3 col-lg-2">Added by</dt>
                            <dd class="col-sm-9">{{ coffin.user }}</dd>
                        </dl>
                    </div>
                </td>
                <td class="d-none d-md-table-cell text-right">PGK {{ coffin.print_price }}</td>
                <td>
                    <a class="text-info" href="{% url 'products:edit' 'coffin' coffin.id %}">Edit</a>
                    &nbsp;
                    <a class="text-danger" href="javascript:prompt_delete({{coffin.id}})">Delete</a>
                </td>
            </tr>
{% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block modals %}
    <div id="modal-coffin-delete" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="{% url 'products:delete' 'coffin' %}" method="post">
                    {% csrf_token %}
                    <input id="modal-coffin-delete-id" type="hidden" name="object_id" value="0">
                    <div class="modal-body">
                        Are you sure you want to delete this record?
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-sm btn-success">Yes</button>
                        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">No</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    function prompt_delete(id)
    {
        $('#modal-coffin-delete-id').val(id);
        $('#modal-coffin-delete').modal('show');
    }
</script>
{% endblock %}

products/templates/products/menu.html
<ul class="nav nav-tabs mb-4">
    <li class="nav-item">
        <a class="nav-link {% if menu_tab == 'coffins' %}active{% endif %}" href="{% url 'products:list' 'coffin' %}">Coffins</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if menu_tab == 'services' %}active{% endif %}" href="{% url 'products:list' 'service' %}">Services</a>
    </li>
    <li class="ml-auto nav-item">
{% if menu_tab == 'coffins' %}
        <a class="nav-link" href="{% url 'products:edit' 'coffin' 0 %}">Add new coffin</a>
{% else %}
        <a class="nav-link" href="{% url 'products:edit' 'service' 0 %}">Add new service</a>
{% endif %}
    </li>
</ul>

products/templates/products/products.html
{% extends "home/base.html" %}

{% block title %}Products - PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='products' %}
{% endblock %}

{% block content %}
{% include 'products/menu.html' with menu_tab='products' %}

<div class="card mb-4">
    <div class="card-header">
        Products
    </div>
    <table id="table-accordion" class="table table-hover table-bordered accordion mb-0">
        <thead>
            <tr>
                <th class="table-col-no">#</th>
                <th>Name</th>
                <th class="table-col-action">Action</th>
            </tr>
        </thead>
        <tbody>
{% for product in products %}
            <tr data-toggle="collapse" data-target="#product-{{product.id}}">
                <td>{{ forloop.counter }}</td>
                <td>
                    {{ product.name }}
                    <div id="product-{{product.id}}" class="collapse small" data-parent="#table-accordion">
                        <hr>
                        <p>Added by {{ product.user }}</p>
                    </div>
                </td>
                <td>
                    <a class="text-info" href="{% url 'products:product_edit' product.id %}">Edit</a>
                    &nbsp;
                    <a class="text-danger" href="javascript:prompt_delete({{product.id}})">Delete</a>
                </td>
            </tr>
{% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block modals %}
    <div id="modal-product-delete" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="{% url 'products:product_delete' %}" method="post">
                    {% csrf_token %}
                    <input id="modal-product-delete-id" type="hidden" name="product_id" value="0">
                    <div class="modal-body">
                        Are you sure you want to delete this record?
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-sm btn-success">Yes</button>
                        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">No</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    function prompt_delete(id)
    {
        $('#modal-product-delete-id').val(id);
        $('#modal-product-delete').modal('show');
    }
{% endblock %}

products/templates/products/service_edit.html
{% extends "home/base.html" %}

{% block title %}Edit Product - PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='products' %}
{% endblock %}

{% block content %}
<a href="{% url 'products:list' 'service' %}" class="btn btn-link mb-4">Back to Services list</a>
<div class="card mb-4">
    <div class="card-header">
        Service Info
    </div>
    <div class="card-body">
        <form class="" action="{% url 'products:save' 'service' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="object_id" value="{{ service.id }}">
            <fieldset class="mb-4">
                <div class="form-group row">
                    <label for="form-service-code" class="col-md-2 col-form-label">Code</label>
                    <div class="col-md-3">
                        <input type="text" class="form-control" id="form-service-code" name="code"
                            placeholder="Enter code" maxlength="15" value="{{ service.code }}" required>
                        <small id="form-service-code-help" class="form-text text-muted">Code of the service</small>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-service-name" class="col-md-2 col-form-label">Name</label>
                    <div class="col-md-10">
                        <input type="text" class="form-control" id="form-service-name" name="name"
                            placeholder="Enter name" maxlength="255" value="{{ service.name }}" required>
                        <small id="form-service-name-help" class="form-text text-muted">Name of the service</small>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-service-description" class="col-md-2 col-form-label">Description</label>
                    <div class="col-md-10">
                        <textarea class="form-control" id="form-service-description" name="description"
                            rows="3" placeholder="Enter description">{{ service.description }}</textarea>
                        <small id="form-service-description-help" class="form-text text-muted">Description of the service</small>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="form-service-price" class="col-md-2 col-form-label">Price</label>
                    <div class="col-md-3">
                        <input type="number" class="form-control" id="form-service-price" name="price"
                            placeholder="Enter price" min="0" value="{{ service.price }}" required>
                        <small id="form-service-price-help" class="form-text text-muted">Price of the service</small>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <div class="form-group mb-0 row">
                    <div class="offset-md-2 col-md-3">
                        <button type="submit" class="btn btn-success"
                            name="next" value="list">Save</button>
                        <button type="submit" class="btn btn-success"
                            name="next" value="add">Save &amp; add another</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

products/templates/products/services.html
{% extends "home/base.html" %}

{% block title %}Services - PFS Manager{% endblock %}

{% block navbar %}
{% include 'home/navbar.html' with navbar_tab='products' %}
{% endblock %}

{% block content %}
{% include 'products/menu.html' with menu_tab='services' %}

<div class="card mb-4">
    <div class="card-header">
        Services
    </div>
    <table id="table-accordion" class="table table-hover table-bordered accordion mb-0">
        <thead>
            <tr>
                <th class="table-col-no">#</th>
                <th class="table-col-code d-none d-md-table-cell">Code</th>
                <th>Name</th>
                <th class="table-col-price d-none d-lg-table-cell">Price</th>
                <th class="table-col-action d-none d-md-table-cell">Action</th>
            </tr>
        </thead>
        <tbody>
{% for service in services %}
            <tr data-toggle="collapse" data-target="#service-{{service.id}}">
                <td>{{ forloop.counter }}</td>
                <td class="d-none d-md-table-cell">{{ service.code }}</td>
                <td>
                    <div class="d-md-none small">
                        [{{ service.code }}]
                    </div>
                    <p>{{ service.name }}</p>
                    <div id="service-{{service.id}}" class="collapse small" data-parent="#table-accordion">
                        <dl class="row mb-0">
                            <dt class="col-md-4 col-xl-2">Description</dt>
                            <dd class="col-md-8">{{ service.short_description }}</dd>
                        </dl>
                        <dl class="d-lg-none row mb-0">
                            <dt class="col-md-4 col-xl-2">Price</dt>
                            <dd class="col-md-8">PGK {{ service.print_price }}</dd>
                        </dl>
                        <dl class="row mb-0">
                            <dt class="col-md-4 col-xl-2">Added by</dt>
                            <dd class="col-md-8">{{ service.user }}</dd>
                        </dl>
                    </div>
                    <div class="d-md-none">
                        <a class="btn btn-sm btn-info" href="{% url 'products:edit' 'service' service.id %}">Edit</a>
                        <a class="btn btn-sm btn-danger" href="javascript:prompt_delete({{service.id}})">Delete</a>
                    </div>
                </td>
                <td class="d-none d-lg-table-cell text-right">PGK {{ service.print_price }}</td>
                <td class="d-none d-md-table-cell">
                    <a class="btn btn-sm btn-info" href="{% url 'products:edit' 'service' service.id %}">Edit</a>
                    <a class="btn btn-sm btn-danger" href="javascript:prompt_delete({{service.id}})">Delete</a>
                </td>
            </tr>
{% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block modals %}
    <div id="modal-service-delete" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="{% url 'products:delete' 'service' %}" method="post">
                    {% csrf_token %}
                    <input id="modal-service-delete-id" type="hidden" name="object_id" value="0">
                    <div class="modal-body">
                        Are you sure you want to delete this record?
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-sm btn-success">Yes</button>
                        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">No</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    function prompt_delete(id)
    {
        $('#modal-service-delete-id').val(id);
        $('#modal-service-delete').modal('show');
    }
</script>
{% endblock %}